### ISSUE TITLE
Still alive??

### ISSUE THREAD

**Issue by salvadorc17** [nadult/FreeFT#2]
Is this still alive???

**Comment by nadult** [comment]
No :)

**Comment by salvadorc17** [comment]
Really?? development halted??

**Comment by nadult** [comment]
Yes, I'm working on a different project and I'm not planning to revive FreeFT anytime soon (if ever).

**Comment by salvadorc17** [comment]
Ok thanks for help

**Comment by JanSimek** [comment]
In case you are interested, there is a similar project attempting to create Fallout 2 engine replacement: https://github.com/falltergeist/falltergeist
