### ISSUE TITLE
Editor support for entities??

### ISSUE THREAD

**Issue by salvadorc17** [nadult/FreeFT#3]
When i load a converted map i cannot see entities...

**Comment by nadult** [comment]
Hi,

Editor does have support for entities, but when importing map from original Fallout Tactics, only tiles are imported. Entity types in FreeFT are quite different than those in FT.

**Comment by salvadorc17** [comment]
How different?? i cant even see entites directory into data..

**Comment by nadult** [comment]
If you want to import entities from original Fallout Tactics maps, then you would have to write some code. I've only written importer for tiles:
https://github.com/nadult/FreeFT/blob/master/src/game/tile_map_legacy.cpp

**Comment by salvadorc17** [comment]
That will be difficult i dont know FT map file formats..

**Comment by nadult** [comment]
That's where reverse enginerring comes into play :). I didn't know the format for tile maps either, yet somehow I managed to write the importer.
